[package]
name = "useful_shit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
serde = "1.0.130"
serde_json = "1.0.67"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.14"